#!/usr/bin/env python3
"""Minimal CLI for validating the first AI novel workflow loop."""

from __future__ import annotations

import argparse
import json
import re
from collections import defaultdict
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SYSTEM_DIR = ROOT / "novel_writing_system"
PLANNING_DIR = SYSTEM_DIR / "大纲管理" / "临时规划"
WRITING_DIR = SYSTEM_DIR / "章节写作"

CURRENT_STATE_PATH = PLANNING_DIR / ".current_state.json"
CHARACTER_STATE_PATH = PLANNING_DIR / ".character_states.json"


@dataclass
class ChapterMetadata:
    path: Path
    chapter_number: int | None
    title: str
    previous_summary: str
    is_auto_generated: bool
    updated_at: str


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, data: dict[str, Any]) -> None:
    path.write_text(
        json.dumps(data, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def extract_chapter_number(name: str) -> int | None:
    match = re.search(r"第0*(\d+)章", name)
    if match:
        return int(match.group(1))
    return None


def collect_metadata() -> list[ChapterMetadata]:
    metadata_entries: list[ChapterMetadata] = []
    for path in sorted(WRITING_DIR.rglob("metadata.json")):
        payload = load_json(path)
        metadata_entries.append(
            ChapterMetadata(
                path=path,
                chapter_number=payload.get("chapterNumber")
                or extract_chapter_number(path.parent.name),
                title=payload.get("title", ""),
                previous_summary=payload.get("previousSummary", ""),
                is_auto_generated=bool(payload.get("isAutoGenerated")),
                updated_at=payload.get("updatedAt", ""),
            )
        )
    return metadata_entries


def choose_canonical_metadata(entries: list[ChapterMetadata]) -> dict[int, ChapterMetadata]:
    canonical: dict[int, ChapterMetadata] = {}
    grouped: dict[int, list[ChapterMetadata]] = defaultdict(list)
    for entry in entries:
        if entry.chapter_number is None:
            continue
        grouped[entry.chapter_number].append(entry)

    for chapter_number, chapter_entries in grouped.items():
        ordered = sorted(
            chapter_entries,
            key=lambda item: (
                item.is_auto_generated,
                len(item.path.parent.name),
                str(item.path),
            ),
        )
        canonical[chapter_number] = ordered[0]
    return canonical


def collect_drafts() -> list[Path]:
    return sorted((WRITING_DIR / "草稿").glob("*.md"))


def collect_character_files() -> list[Path]:
    return sorted((SYSTEM_DIR / "人物管理").rglob("人物_*.md"))


def project_status() -> dict[str, Any]:
    current_state = load_json(CURRENT_STATE_PATH)
    character_state = load_json(CHARACTER_STATE_PATH)
    metadata_entries = collect_metadata()
    canonical_metadata = choose_canonical_metadata(metadata_entries)
    drafts = collect_drafts()
    characters = collect_character_files()

    duplicate_chapters = {
        chapter_number: [str(entry.path.relative_to(ROOT)) for entry in entries]
        for chapter_number, entries in group_metadata(metadata_entries).items()
        if len(entries) > 1
    }

    return {
        "current_state": current_state,
        "character_state_summary": {
            "tracked_character_count": len(character_state.get("characters", {})),
            "last_updated": character_state.get("metadata", {}).get("last_updated", ""),
            "current_chapter": character_state.get("metadata", {}).get("current_chapter", 0),
        },
        "content_summary": {
            "character_file_count": len(characters),
            "draft_count": len(drafts),
            "metadata_count": len(metadata_entries),
            "canonical_metadata_count": len(canonical_metadata),
            "duplicate_chapters": duplicate_chapters,
        },
    }


def group_metadata(entries: list[ChapterMetadata]) -> dict[int, list[ChapterMetadata]]:
    grouped: dict[int, list[ChapterMetadata]] = defaultdict(list)
    for entry in entries:
        if entry.chapter_number is not None:
            grouped[entry.chapter_number].append(entry)
    return grouped


def validate_repo() -> list[str]:
    issues: list[str] = []
    current_state = load_json(CURRENT_STATE_PATH)
    character_state = load_json(CHARACTER_STATE_PATH)
    metadata_entries = collect_metadata()
    drafts = collect_drafts()

    grouped = group_metadata(metadata_entries)
    for chapter_number, entries in sorted(grouped.items()):
        if len(entries) > 1:
            issue_paths = ", ".join(str(entry.path.relative_to(ROOT)) for entry in entries)
            issues.append(f"chapter {chapter_number} has duplicate metadata files: {issue_paths}")

    current_chapter = int(current_state.get("current_chapter", 0))
    if current_chapter == 0 and drafts:
        issues.append("current_state.current_chapter is 0 even though chapter drafts already exist")

    if not current_state.get("context", {}).get("active_characters"):
        issues.append("current_state.context.active_characters is empty")

    if not current_state.get("context", {}).get("active_plot_hooks"):
        issues.append("current_state.context.active_plot_hooks is empty")

    if not current_state.get("context", {}).get("emotional_tone"):
        issues.append("current_state.context.emotional_tone is empty")

    tracked_chapter = int(character_state.get("metadata", {}).get("current_chapter", 0))
    if tracked_chapter != current_chapter:
        issues.append(
            "character state current_chapter does not match current_state.current_chapter"
        )

    if current_chapter > 0 and not character_state.get("characters"):
        issues.append("character state has no tracked characters for an active chapter")

    return issues


def chapter_context(chapter: int) -> dict[str, Any]:
    current_state = load_json(CURRENT_STATE_PATH)
    character_state = load_json(CHARACTER_STATE_PATH)
    metadata_entries = collect_metadata()
    canonical_metadata = choose_canonical_metadata(metadata_entries)
    entry = canonical_metadata.get(chapter)

    draft_candidates = [
        path for path in collect_drafts() if extract_chapter_number(path.name) == chapter
    ]

    return {
        "requested_chapter": chapter,
        "current_state": current_state,
        "metadata": {
            "path": str(entry.path.relative_to(ROOT)) if entry else "",
            "title": entry.title if entry else "",
            "previous_summary": entry.previous_summary if entry else "",
            "is_auto_generated": entry.is_auto_generated if entry else False,
            "updated_at": entry.updated_at if entry else "",
        },
        "drafts": [str(path.relative_to(ROOT)) for path in draft_candidates],
        "tracked_characters": character_state.get("characters", {}),
    }


def chapter_check(chapter: int) -> dict[str, Any]:
    current_state = load_json(CURRENT_STATE_PATH)
    character_state = load_json(CHARACTER_STATE_PATH)
    canonical_metadata = choose_canonical_metadata(collect_metadata())
    entry = canonical_metadata.get(chapter)
    draft_candidates = [
        path for path in collect_drafts() if extract_chapter_number(path.name) == chapter
    ]

    issues: list[str] = []
    warnings: list[str] = []

    if entry is None:
        issues.append(f"chapter {chapter} has no metadata")
    else:
        if not entry.title.strip():
            issues.append(f"chapter {chapter} metadata.title is empty")
        if not entry.previous_summary.strip():
            warnings.append(f"chapter {chapter} metadata.previousSummary is empty")
        if entry.is_auto_generated:
            warnings.append(f"chapter {chapter} metadata is still marked auto-generated")

    if not draft_candidates:
        issues.append(f"chapter {chapter} has no draft markdown file")
    elif len(draft_candidates) > 1:
        warnings.append(
            "chapter "
            f"{chapter} has multiple draft files: "
            + ", ".join(str(path.relative_to(ROOT)) for path in draft_candidates)
        )

    active_characters = current_state.get("context", {}).get("active_characters", [])
    tracked_characters = character_state.get("characters", {})
    missing_tracking = [name for name in active_characters if name not in tracked_characters]
    if missing_tracking:
        warnings.append(
            "active characters missing from character state: " + ", ".join(missing_tracking)
        )

    if int(current_state.get("current_chapter", 0)) < chapter:
        warnings.append(
            f"current_state.current_chapter={current_state.get('current_chapter', 0)} "
            f"is behind requested chapter {chapter}"
        )

    return {
        "chapter": chapter,
        "metadata_path": str(entry.path.relative_to(ROOT)) if entry else "",
        "drafts": [str(path.relative_to(ROOT)) for path in draft_candidates],
        "issues": issues,
        "warnings": warnings,
        "ok": not issues,
    }


def sync_state(
    chapter: int,
    state_name: str,
    unit_name: str | None,
    characters: list[str],
    plot_hooks: list[str],
    emotional_tone: str | None,
) -> dict[str, Any]:
    current_state = load_json(CURRENT_STATE_PATH)
    character_state = load_json(CHARACTER_STATE_PATH)

    previous_state = current_state.get("current_state", "")
    current_state["current_state"] = state_name
    current_state["current_chapter"] = chapter
    if unit_name:
        current_state["current_unit"] = unit_name
    current_state["started_at"] = current_state.get("started_at") or now_iso()
    current_state.setdefault("context", {})
    current_state["context"]["active_characters"] = characters
    current_state["context"]["active_plot_hooks"] = plot_hooks
    current_state["context"]["emotional_tone"] = emotional_tone or ""
    current_state.setdefault("history", [])
    current_state["history"].append(
        {
            "timestamp": now_iso(),
            "from_state": previous_state,
            "to_state": state_name,
            "chapter": chapter,
        }
    )

    character_state.setdefault("metadata", {})
    character_state["metadata"]["last_updated"] = now_iso()
    character_state["metadata"]["current_chapter"] = chapter
    character_state.setdefault("characters", {})
    for character_name in characters:
        character_state["characters"].setdefault(character_name, {})
        character_state["characters"][character_name]["last_seen_chapter"] = chapter
        character_state["characters"][character_name]["active"] = True
        character_state["characters"][character_name]["last_updated"] = now_iso()

    write_json(CURRENT_STATE_PATH, current_state)
    write_json(CHARACTER_STATE_PATH, character_state)

    return {
        "updated_current_state": str(CURRENT_STATE_PATH.relative_to(ROOT)),
        "updated_character_state": str(CHARACTER_STATE_PATH.relative_to(ROOT)),
        "chapter": chapter,
        "state": state_name,
        "active_characters": characters,
        "active_plot_hooks": plot_hooks,
        "emotional_tone": emotional_tone or "",
    }


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Minimal AI novel MVP CLI")
    subparsers = parser.add_subparsers(dest="command", required=True)

    subparsers.add_parser("status", help="Show project status summary")
    subparsers.add_parser("check", help="Validate repo issues")

    context_parser = subparsers.add_parser(
        "chapter-context", help="Build context package for a chapter"
    )
    context_parser.add_argument("--chapter", type=int, required=True)

    chapter_check_parser = subparsers.add_parser(
        "chapter-check", help="Validate chapter-level assets and state"
    )
    chapter_check_parser.add_argument("--chapter", type=int, required=True)

    sync_parser = subparsers.add_parser("sync-state", help="Update minimal state files")
    sync_parser.add_argument("--chapter", type=int, required=True)
    sync_parser.add_argument("--state", required=True)
    sync_parser.add_argument("--unit")
    sync_parser.add_argument("--characters", required=True)
    sync_parser.add_argument("--plot-hooks", required=True)
    sync_parser.add_argument("--tone")

    return parser


def print_json(data: Any) -> None:
    print(json.dumps(data, ensure_ascii=False, indent=2))


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    if args.command == "status":
        print_json(project_status())
        return 0

    if args.command == "check":
        issues = validate_repo()
        print_json({"issues": issues, "issue_count": len(issues)})
        return 1 if issues else 0

    if args.command == "chapter-context":
        print_json(chapter_context(args.chapter))
        return 0

    if args.command == "chapter-check":
        result = chapter_check(args.chapter)
        print_json(result)
        return 1 if result["issues"] else 0

    if args.command == "sync-state":
        characters = [item.strip() for item in args.characters.split(",") if item.strip()]
        plot_hooks = [item.strip() for item in args.plot_hooks.split(",") if item.strip()]
        print_json(
            sync_state(
                chapter=args.chapter,
                state_name=args.state,
                unit_name=args.unit,
                characters=characters,
                plot_hooks=plot_hooks,
                emotional_tone=args.tone,
            )
        )
        return 0

    parser.error("unknown command")
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
