/**
 * 集中化文案管理
 *
 * 规则来源：
 *   - docs/design/ui/47-ui-copy-guidelines.md（UI 文案指南）
 *   - AGENTS.md § UI 设计驱动（Design-Driven）
 *
 * 约束：
 *   - 所有用户可见文字必须集中在此文件
 *   - 组件中禁止硬编码中文或英文 UI 文案
 *   - Canonical 英文术语（card_type / intent / state）不出现在面向作者的 UI 中
 *   - 新增文案前先核对 47-ui-copy-guidelines.md 的禁止用语表
 */

// ============================================================
// 通用
// ============================================================

export const APP_NAME = "AI Novel Studio";

export const BUTTON = {
  confirm: "确认",
  cancel: "取消",
  close: "关闭",
  save: "保存",
  delete: "删除",
  edit: "编辑",
  back: "返回",
  next: "下一步",
  submit: "提交",
  retry: "重试",
  copy: "复制",
  export: "导出",
  import: "导入",
  search: "搜索",
  filter: "筛选",
  reset: "重置",
  refresh: "刷新",
  more: "更多",
  expand: "展开",
  collapse: "收起",
  add: "添加",
  remove: "移除",
  create: "创建",
  update: "更新",
  archive: "归档",
  restore: "恢复",
  deprecate: "标记过期",
  lock: "锁定",
  unlock: "解锁",
} as const;

// ============================================================
// 状态
// ============================================================

export const STATUS = {
  loading: "加载中...",
  error: "出错了",
  empty: "暂无内容",
  noResults: "未找到匹配结果",
  connecting: "正在连接...",
  connected: "已连接",
  disconnected: "连接已断开",
  saving: "保存中...",
  saved: "已保存",
  deleting: "删除中...",
  deleted: "已删除",
  processing: "处理中...",
  completed: "已完成",
  failed: "失败",
  pending: "待处理",
  active: "进行中",
  archived: "已归档",
  deprecated: "已过期",
  locked: "已锁定",
} as const;

// ============================================================
// 卡片系统（docs/design/ui/42-card-system.md）
// ============================================================

export const CARD = {
  clarification: {
    title: "需要澄清",
    description: "AI 需要更多信息才能继续",
  },
  qualityReview: {
    title: (count: number) => `质量复核：发现 ${count} 项可改进问题`,
    evidencePrefix: "正文证据：",
    unavailableTitle: "本次质量复核未完成",
    unavailableBody: "质量评审未能完成，以下原稿仍可由你审阅与采纳；系统不会据此自动改写或判定通过。",
    reviseButton: "按这些问题重写",
    reviseHint: "重写会另生成一份修订草稿供你对比；原草稿保留，不会自动采纳。",
    gateLabels: {
      "quality_gate.worldrule_conflict": "设定冲突",
      "quality_gate.character_logic": "人物逻辑",
      "quality_gate.timeline_and_state": "时间线与状态",
      "quality_gate.foreshadowing": "伏笔设定",
      "quality_gate.knowledge_boundary": "信息越界",
      "quality_gate.pacing": "故事节奏",
      "quality_gate.payoff_validity": "爽点成立",
      "quality_gate.web_hook_strength": "Hook 强度",
      "quality_gate.power_scaling": "战力膨胀",
      "quality_gate.serialization_retention": "网文留存",
      "quality_gate.style_fit": "风格与句式",
    } as Record<string, string>,
  },
  confirmation: {
    title: "请确认",
    description: "请确认以下内容是否符合预期",
    confirmLabel: "确认执行",
    rejectLabel: "取消",
  },
  warning: {
    title: "注意",
    description: "以下内容可能存在问题",
  },
  checkpoint: {
    title: "检查点",
    description: "长跑任务已暂停，请决定下一步",
    resumeLabel: "继续执行",
    cancelLabel: "取消任务",
    branchLabel: "创建分支",
    pendingArtifacts: "待处理产物",
  },
  tentativeArtifact: {
    title: "待采纳",
    description: "AI 建议进行以下改动",
    acceptLabel: "保存到作品",
    acceptProseLabel: "保存为章节正文",
    acceptOutlineLabel: "保存到大纲",
    acceptArchiveLabel: "保存到作品档案",
    discardLabel: "不保存",
    editThenAcceptLabel: "修改后保存",
    editProseThenAcceptLabel: "修改后保存正文",
    editDialogTitle: "修改后保存",
    editDialogDescription: "编辑这段正文后再保存；保存的是你修改后的版本。",
    editPlaceholder: "在此修改正文…",
    editConfirmLabel: "保存修改后的版本",
    editCancelLabel: "取消",
    // 多个角色候选逐项采纳时，把候选名拼到按钮文案，区分采纳的是哪一个候选。
    candidateNameSuffix: (label: string, name: string) => `${label}：${name}`,
  },
  artifactDraft: {
    proseTitle: "章节正文草稿",
    proseDescription:
      "这是待保存章节草稿。保存后会写入章节正文并进入阅读模式；未保存前不会进入作品事实。",
    outlineTitle: "大纲草稿",
    outlineDescription:
      "这是待保存大纲草稿。保存后会进入作品档案的大纲与结构；未保存前只保留为本轮草稿。",
    characterTitle: "角色设定草稿",
    characterEvolutionTitle: "角色演化记忆草稿",
    characterEvolutionDescription:
      "这是待保存的角色演化记忆（成长/当前状态/关系变化）。保存后写入角色记忆并可被后续创作召回，不会改写角色主档案；未保存前不会写入作品事实。",
    worldTitle: "世界设定草稿",
    foreshadowingTitle: "伏笔草稿",
    ruleTitle: "规则草稿",
    constraintTitle: "约束草稿",
    archiveDescription: "这是待保存设定草稿。保存后会进入作品档案；未保存前不会写入作品事实。",
    fallbackTitle: "待保存草稿",
    fallbackDescription: "这是待保存草稿。保存后才会进入作品档案；未保存前不会写入作品事实。",
    rationalePrefix: "创作依据：",
  },
  adoption: {
    title: "已采纳",
    description: "改动已应用到作品",
  },
  adoptionDecision: {
    acceptedTitle: "已保存",
    acceptedDescription: "这条草稿已写入对应的作品位置，后续创作会以保存结果为准。",
    discardedTitle: "已废弃",
    discardedDescription: "这条候选稿已从待处理列表移除，未写入作品事实。",
    editedAcceptedTitle: "已修改后保存",
    editedAcceptedDescription: "系统已按修改内容保存，原草稿保留为来源记录。",
    unknownTitle: "已处理",
    unknownDescription: "这条候选稿已有处理结果，不再需要重复操作。",
    artifactFallbackTitle: "创作设定",
    openReadingModeLabel: "查看已采纳内容",
  },
  longRunProgress: {
    title: "长跑进度",
    description: "AI 正在执行长时间任务",
  },
  result: {
    title: "执行完成",
    description: "操作已完成",
  },
  failure: {
    title: "执行失败",
    description: "操作未能完成",
    retryLabel: "重试",
    discardLabel: "放弃",
  },
  escalation: {
    title: "需要关注",
    description: "此操作需要你的特别关注",
  },
} as const;

// ============================================================
// 工作台（docs/design/ui/41-workbench-layout.md）
// ============================================================

export const WORKBENCH = {
  userDisplayName: "你",
  assistantDisplayNameDefault: "AI",
  assistantDisplayNameAction: "AI 名称",
  assistantDisplayNameTitle: "AI 显示名",
  assistantDisplayNameDescription: "只改变当前作品里的界面称呼。",
  assistantDisplayNameField: "显示名",
  assistantDisplayNamePlaceholder: "AI",
  assistantDisplayNameSave: "保存名称",
  assistantDisplayNameReset: "恢复默认",
  assistantDisplayNameSaving: "保存中",
  assistantDisplayNameFailure: "名称保存失败，请重试。",
  inputPlaceholder: "输入你的想法、问题或指令...",
  send: "发送",
  thinking: "思考中...",
  emptyState: "开始对话，创作你的作品",
  welcomeMessage:
    "欢迎使用 AI Novel Studio！\n\n本产品需要连接大语言模型（LLM）才能工作。\n请确保 LM Studio 已启动并加载模型（默认端口 1234）。\n\n你可以这样开始：\n• 「我想创建一部玄幻小说」\n• 「写一本都市小说，核心卖点是商战复仇」\n• 「帮我创作一部科幻小说，目标读者是大学生」\n\n输入你的想法，我们开始创作吧！",
  startupConnecting: "正在连接工作台，请稍候…",
  startupFailurePrefix: "作品上下文加载失败，工作台未连接。",
  startupFailureLoadWork: "无法获取或创建作品：",
  startupFailureResumeSession: "无法恢复作品会话：",
  startupFailureJoinMismatch: "Channel 返回的作品/会话与启动上下文不一致：",
  sendFailure: "发送失败，请重试。",
  candidatePanelTitle: "可讨论方向",
  candidateContinueLabel: "继续讨论",
  candidateContinueTitle: "把这个方向作为下一轮讨论上下文，不会写入作品档案或章节正文。",
  candidateAdoptLabel: "设为后续方向",
  candidateAdoptTitle: "把这个方向作为后续创作依据；不会直接写入章节正文。",
  frameBadges: {
    creativeExploration: "探索方向",
    executionCandidate: "生成草稿",
    downgrade: "降级为对话",
    casualReply: "自然回复",
    questionAnswer: "回答问题",
    metaDiscussion: "创作讨论",
    confirmationAnswer: "确认回合",
    fallback: "本轮回应",
  },
  frameBadgeTitle: (label: string, goal: string | null) => (goal ? `${label}：${goal}` : label),
  workMenuTitle: "作品",
  workMenuCurrent: "当前",
  workMenuCreate: "新建作品",
  workMenuQuickCreate: "快速新建未命名作品",
  workMenuRename: "重命名",
  workMenuDelete: "删除作品",
  workMenuRefresh: "刷新作品列表",
  workMenuSwitching: "切换中",
  workMenuEmpty: "暂无作品",
  workMenuDuplicateIndex: (index: number) => `第 ${index} 个`,
  unnamedWorkTitle: "未命名作品",
  workCreateDialogTitle: "新建作品",
  workRenameDialogTitle: "修改作品名",
  workDeleteDialogTitle: "删除作品",
  workTitleField: "作品名",
  workTitlePlaceholder: "输入作品名",
  workDeleteDescription: (title: string) => `确认删除「${title}」？`,
  workDeleteDetail: "作品会从默认列表移出，当前窗口会切换到其它作品。",
  workTitleRequired: "请输入 1-120 个字符的作品名。",
  workUpdateFailure: "作品更新失败，请重试。",
  workDeleteFailure: "作品删除失败，请重试。",
  switchFailurePrefix: "作品切换失败：",
  createWorkFailure: "新建作品失败，请重试。",
  adoptionIncomplete: "采纳未完成，请查看系统提示后重试。",
  actionFailure: "操作失败，请重试。",
  actionDuplicate: "该操作已处理，系统已避免重复执行。",
  actionUnavailable: "当前动作不可用，请刷新或继续对话。",
  actionConfirm: "确认执行",
  actionReject: "拒绝",
  actionCancel: "取消",
  actionAnswer: "回答",
  acceptProseActionTitle: "保存后会写入章节正文，并出现在阅读模式。",
  acceptOutlineActionTitle: "保存后会进入作品档案的大纲与结构。",
  acceptArchiveActionTitle: "保存后会进入作品档案，不会直接写章节正文。",
  acceptGenericActionTitle: "保存后才会进入作品档案或作品事实。",
  discardActionTitle: "不保存这份草稿，不会写入作品。",
  editProseActionTitle: "先修改正文，再保存为章节正文。",
  editGenericActionTitle: "先修改内容，再保存到作品。",
  readingModeLabel: "阅读",
  memoryLabel: "记忆",
  wholeBookLabel: "全书",
  taskIdleLabel: "无任务",
  taskRunningLabel: (progress: number) => `任务 ${progress}%`,
  taskCheckpointLabel: "任务检查点",
  taskCompletedLabel: "任务完成",
  taskFailedLabel: "任务失败",
  taskSwitchingLabel: "切换中",
  modelCheckingLabel: "模型检测中",
  modelConnectedLabel: "模型已连接",
  modelDisconnectedLabel: "模型未连接",
  modelStatusTitle: (model: string) => `当前模型：${model}`,
  modelDisconnectedTitle: "请检查当前模型供应商配置和连接状态",
  modelProviderAction: "模型设置",
  modelProviderTitle: "模型供应商",
  modelProviderDescription: "选择当前作品对话使用的模型供应商。",
  modelProviderField: "供应商",
  modelProviderSubscriptionHint:
    "订阅认证使用 ChatGPT 订阅令牌，与 OpenAI（API Key）是同一供应商的两种认证方式，密钥分别保存。",
  modelProviderModelField: "模型",
  modelProviderEndpointField: "端点",
  modelProviderEndpointInvalid: "端点必须是完整的 http(s) URL。",
  modelProviderApiKeyField: "API Key",
  modelProviderApiKeyPlaceholder: "保留已保存的 Key",
  modelProviderApiKeyConfigured: "已保存 Key",
  modelProviderClearApiKey: "清除已保存 Key",
  modelProviderThinkingField: "思考模式",
  modelProviderThinkingDisabled: "关闭",
  modelProviderThinkingEnabled: "开启",
  modelProviderReasoningField: "推理强度",
  modelProviderReasoningDefault: "默认（不指定）",
  modelProviderReasoningLow: "低",
  modelProviderReasoningMedium: "中",
  modelProviderReasoningHigh: "高",
  modelProviderTest: "测试连接",
  modelProviderTesting: "测试中",
  modelProviderSave: "保存并切换",
  modelProviderSaving: "保存中",
  modelProviderRefreshModels: "刷新模型列表",
  modelProviderModelsLoading: "模型加载中",
  modelProviderNoModels: "暂无可选模型",
  modelProviderModelsUnsupported: "该供应商无需选择模型。",
  modelProviderLoadFailure: "模型设置加载失败。",
  modelProviderLoadFailureDetail: (detail: string) => `模型设置加载失败：${detail}`,
  modelProviderSaveFailure: "模型设置保存失败。",
  modelProviderSaveFailureDetail: (detail: string) => `模型设置保存失败：${detail}`,
  modelProviderTestSuccess: "连接可用。",
  modelProviderTestFailure: "连接不可用，请检查配置。",
  modelProviderTestFailureDetail: (detail: string) => `连接不可用：${detail}`,
  modelProviderModelsLoadFailure: "模型列表加载失败。",
  modelProviderModelsLoadFailureDetail: (detail: string) => `模型列表加载失败：${detail}`,
  syncStatusLabel: (label: string) => `同步${label}`,
  archiveRailTitle: "作品档案",
  archiveRailOpen: "打开档案",
  archiveRailDetail: "查看详情",
  pendingAdoptionsPrefix: "待采纳",
  sessionSearchPlaceholder: "搜索会话",
  sessionCreate: "新建会话",
  sessionNewTitle: "新会话",
  sessionCreateFailure: "新建会话失败，请重试。",
  sessionReadOnlyTitle: "历史会话",
  sessionReadOnlyDescription: "正在只读查看历史 transcript。新输入仍会回到当前活跃会话。",
  sessionBackToActive: "返回当前会话",
  sessionBranchFromHistory: "从这里继续",
  sessionBranchTitle: (title: string) => `${title} 的延续`,
  sessionBranchFailure: "从历史会话继续失败，请重试。",
  sessionArchive: "归档会话",
  sessionArchiveFailure: "会话归档失败，请重试。",
  sessionOpenFailure: "会话打开失败，请重试。",
} as const;

// ============================================================
// 决策溯源（docs/design/acceptance/author/AU-07-trace-and-replay.md）
// ============================================================

export const TRACE = {
  actionLabel: "为什么",
  actionTitle: "查看这轮回应的依据",
  contextLabel: "参考来源",
  noContext: "本轮没有使用额外作品上下文。",
  detailLabel: "补充说明",
  integrityNote: "解释来自本轮已保存的 trace 摘要，不会重新调用模型或改写作品。",
  replayUnavailable: "这轮没有可显示的已保存解释。",
  replayComplete: "已从持久 trace 生成结构化回放。",
  replayPartial: "这轮 trace 不完整，只展示已保存的部分解释。",
  replayNoProvider: "回放只读取已保存记录，不会重新调用模型。",
  previousDialogueSummary: (topic: string) => `上一轮围绕「${topic}」展开，AI 已给出回应。`,
  previousAuthorMention: (topic: string) => `上一轮作者提到「${topic}」。`,
  previousAssistantReply: "上一轮 AI 已给出回应。",
  decisions: {
    replyOnly: "自然回复",
    exploration: "探索方向",
    executionCandidate: "生成草稿",
    downgrade: "降级为对话",
    confirmationRequired: "需要确认",
    clarificationRequired: "需要补充信息",
    rejected: "已拒绝执行",
    recovery: "已降级恢复",
    toolAllowed: "允许工具",
    toolDispatched: "已调用工具",
    adoptTentative: "已采用候选",
    unknown: "已记录",
  },
  reasons: {
    noToolNeeded: "本轮只需要自然语言回应，不需要调用工具或写入作品状态。",
    exploratoryOnly: "本轮是在探索创作方向，候选内容不会自动写入作品档案、设定或正文。",
    userRequestedDiscussion: "你提出的是讨论或解释请求，系统没有执行写入动作。",
    toolWasDispatched: "本轮调用了创作工具，工具结果仍需通过卡片确认后才会进入作品。",
    microPlanEvaluated: "系统先评估了执行计划，再按权限和范围决定是否继续。",
    microPlanFailed: "执行计划生成失败，系统已降级为安全的自然回复。",
    confirmationRequired: "本轮需要你的确认，系统不会在确认前执行高影响操作。",
    clarificationRequired: "系统缺少必要信息，需补充后才能继续推进。",
    rejected: "系统拒绝执行本轮请求，并保留了拒绝原因摘要。",
    safeFallback: "系统保留了本轮的安全解释摘要。",
  },
  gates: {
    actionScope: "当前请求超出本轮可执行范围。",
    plannerBoundary: "计划没有通过执行边界检查。",
    authorityBudget: "权限或预算策略要求先暂停。",
    confirmationRequired: "此操作需要作者明确确认。",
    generic: "系统记录了一个执行门禁原因。",
  },
  reasonCodes: {
    gatesPassed: "执行门禁已通过。",
    candidateAdoptedAsTentative: "候选内容先作为待采纳草稿保存。",
    toolResultNotAdoption: "工具结果不是自动采纳的作品事实。",
    generic: "系统记录了一个内部原因，作者视图保留为安全摘要。",
  },
  contextSources: {
    currentWork: "当前作品背景",
    recentDialogue: "近期对话",
    memory: "已确认设定",
    workArchive: "作品档案",
    sessionTranscript: "当前会话记录",
    other: "其他安全来源",
  },
  guidance: {
    qualityDiagnosis: "本轮按质量诊断处理，只给诊断和结构修订建议，不会改写或写入作品。",
    qualityFocus: (focus: string) => `质量关注点：${focus}。`,
    qualityGates: (gates: string) => `小说层质量门：${gates}。`,
    workStateSources: (sources: string) => `作品层依据来自：${sources}。`,
    workStateMissing: "作品层依据缺失或不足，系统已显式标记缺失，不会编造作品事实。",
    missingLimit: "缺少正文片段时，只能基于摘要或上下文给结构建议。",
  },
  recoveryApplied: "系统已使用降级恢复策略。",
  toolUsed: (name: string) => `本轮使用了工具：${name}。`,
  toolWithStatus: (name: string, status: string) =>
    `本轮使用了工具：${name}，结果状态为 ${status}。`,
} as const;

export function candidateContinuationText(title: string, pitch: string): string {
  return `继续聊「${title}」这个方向：${pitch}`;
}

export const WORKSPACE_RUNTIME = {
  currentWorkTitle: "当前作品",
  connectionBooting: "启动中",
  connectionConnecting: "正在连接",
  connectionConnected: "已连接",
  connectionDegraded: "连接不稳定",
  connectionFailed: "离线",
} as const;

// ============================================================
// 作品档案（docs/design/ui/43-structure-panel.md）
// ============================================================

export const STRUCTURE_PANEL = {
  title: "作品档案",
  noWork: "尚未创建设定",
  unnamedWork: "未命名作品",
  stats: {
    volumes: "卷",
    drafts: "草稿",
    characters: "角色",
    memories: "设定",
    pending: "待采纳",
  },
  tabs: {
    overview: "概览",
    outline: "大纲与结构",
    character: "角色",
    foreshadowing: "伏笔",
    rule: "经验规则",
  },
  profile: {
    sectionTitle: "立项设定",
    title: "作品名",
    genre: "题材",
    coreSellingPoint: "核心卖点",
    targetReader: "目标读者",
    tonePreference: "基调",
    revision: "修订号",
    updatedAt: "最后更新",
    emptyValue: "暂未填写",
    statusAccepted: "已确认",
    statusTentative: "待确认",
    statusDiscarded: "已废弃",
    statusUnknown: "状态未明",
    readonlyHint: "这些字段来自当前作品档案，只读展示；需要修改时请回到工作台对话提出修订。",
    reviseLabel: "提出立项修订",
    revisePrompt:
      "我想修订当前作品的立项设定，包括题材、核心卖点、目标读者和基调。请先生成一份待采纳的设定修订草稿，不要直接写入作品档案。",
    readFailureTitle: "作品档案读取失败",
    readFailureDescription: "当前无法读取作品立项设定。请检查同步状态后重试，失败期间不会编造档案内容。",
    readFailureRetryLabel: "重试读取",
  },
  // 模型执行/并发读取期间的档案读取状态：显示加载或读取失败，但保留上次已知快照不空白
  archiveStatus: {
    loading: "正在读取作品档案…",
    refreshing: "正在更新作品档案，先显示上次已知内容…",
    readFailed: "档案读取失败，下面是上次已知内容；模型执行结束后可重试刷新。",
    retryLabel: "重新读取",
  },
  pendingSection: "待采纳内容",
  pendingLabel: "待采纳",
  pendingFallbackTitle: "待审核内容",
  pendingFallbackContent: "这份草稿缺少可预览正文，请回到对话区查看原消息。",
  pendingSections: {
    overview: "待处理内容",
    outline: "待保存大纲",
    character: "待保存角色",
    foreshadowing: "待收录伏笔",
    rule: "待启用规则",
  },
  pendingBadges: {
    overview: "待处理",
    outline: "大纲草稿",
    character: "角色草稿",
    foreshadowing: "伏笔草稿",
    rule: "规则草稿",
  },
  pendingFallbackTitles: {
    overview: "待保存草稿",
    outline: "章节大纲草稿",
    character: "角色草稿",
    foreshadowing: "伏笔草稿",
    rule: "规则草稿",
  },
  pendingDestinations: {
    overview: "保存后进入对应作品档案。",
    outline: "保存后进入作品档案的大纲与结构，并作为后续章节生成依据。",
    character: "保存后进入角色档案。",
    foreshadowing: "保存后进入伏笔追踪。",
    rule: "保存后进入经验规则。",
  },
  pendingAcceptLabels: {
    overview: "保存到作品档案",
    outline: "保存到大纲",
    character: "保存角色",
    foreshadowing: "收入伏笔",
    rule: "启用规则",
  },
  confirmedForeshadowingSection: "已确认设定",
  newForeshadowing: "新增伏笔",
  newForeshadowingPrompt:
    "请基于当前作品背景、设定和剧情走向，帮我想一个能贯穿多章的伏笔或悬念设定。",
  confirmedRulesSection: "已启用规则",
  ruleCountUnit: "条规则",
  newRule: "新建规则",
  newRulePrompt: "请基于当前作品风格和设定，帮我制定一条能约束后续创作的写作规则或风格规则。",
  acceptSetting: "采纳设定",
  requestRevision: "提出修改",
  detailTitle: "详情",
  detailHint: "详情为当前作品的只读档案，修改需回到工作台对话处理。",
  viewDetail: "查看详情",
  selected: "已选中",
  close: "关闭档案",
  detailRows: {
    narrativeRole: "叙事角色",
    role: "身份",
    aliases: "别名",
    state: "状态",
    updatedAt: "最后更新",
    type: "类型",
    scope: "范围",
    source: "来源",
    weight: "权重",
    confidence: "置信度",
    referenceCount: "引用次数",
    version: "版本",
    tags: "标签",
    protection: "保护",
  },
  detailValues: {
    adopted: "已采纳",
    recallable: "可召回",
    notRecallable: "不进入普通召回",
    locked: "已锁定",
  },
  memoryTypeLabels: {
    FORESHADOWING: "伏笔",
    PLOT_FACT: "剧情事实",
    WORLD_RULE: "世界规则",
    CONSTRAINT: "约束",
    STYLE_RULE: "风格规则",
    IDEA: "灵感",
    CHARACTER_PROFILE: "角色演化",
    CURRENT_STATE: "当前状态",
    RELATIONSHIP: "角色关系",
    AUTHOR_PREFERENCE: "作者偏好",
    DRAFT_CONTEXT: "草稿上下文",
  },
  memoryScopeLabels: {
    WORK: "整部作品",
    VOLUME: "当前卷",
    ARC: "当前故事线",
    CHAPTER: "当前章节",
    SCENE: "当前场景",
    GLOBAL: "全局",
  },
  sourceTypeLabels: {
    AUTHOR_CONFIRMED: "作者确认",
    AI_EXTRACTED: "AI 提取",
    IMPORTED: "导入",
    SYSTEM: "系统",
  },
  outlineEmptyTitle: "大纲与结构",
  acceptedChapterPlanSection: "已采纳章节计划",
  chapterCountUnit: "章",
  generateChapterDraft: "生成正文草稿",
  chapterPendingBadge: "待补足",
  chapterWrittenPrefix: "已写",
  chapterWordsUnit: "字",
  outlineEmptyWithWork: "用于把当前作品整理成卷纲和章纲。点击后会在对话区生成规划请求。",
  outlineEmptyNoWork: "先在工作台创建作品，AI 会帮你搭建大纲和分卷结构。",
  startPlanning: "规划卷章结构",
  startPlanningPrompt: "请基于当前作品规划卷章结构，并生成章节大纲。",
  noChapter: "暂无章节",
  acceptedCharactersSection: "已确认角色",
  characterCountUnit: "个角色",
  // 叙事角色分类标签（与后端 NarrativeRole 枚举对齐）
  narrativeRoleLabels: {
    PROTAGONIST: "主角",
    ANTAGONIST: "反派",
    SUPPORTING: "配角",
    MINOR: "次要角色",
    ENSEMBLE_POV: "群像视角",
  } as Record<string, string>,
  // 已有角色但无人标记主角时的诚实提示
  protagonistUnsetHint: "尚未标注主角",
  characterEmptyTitle: "角色档案",
  characterEmptyWithWork:
    "在对话中说「创建角色」或「分析已有角色」，AI 会基于当前作品设计角色草稿。",
  characterEmptyNoWork: "先在工作台创建作品，AI 会在创作过程中自动提取角色信息。",
  createCharacter: "创建角色",
  createCharacterPrompt: "请基于当前作品背景、设定和已有角色，和我一起设计一个新角色。",
  foreshadowingEmptyTitle: "暂无伏笔设定",
  foreshadowingEmptyDesc: "在对话中说「创建主线大纲」或「构建世界观」，AI 会生成设定内容。",
  ruleEmptyTitle: "经验规则",
  ruleEmptyDesc: "在对话中说「导入风格样本」或「构建世界观」，AI 会生成写作规则和设定约束。",
  panelActions: {
    overview: {
      label: "发起综合修订",
      hint: "跨模块调整，转到对话区拆分确认。",
      prompt:
        "我想同时重写第一章、更新主角动机、整理伏笔清单。如果范围太大，请先告诉我如何拆分。",
    },
    outline: {
      label: "发起大纲调整",
      hint: "新增、重排或修改卷章，转到对话区确认。",
      prompt: "我想调整作品的大纲与卷章结构。请先和我确认要改的范围，再生成方案。",
    },
    character: {
      label: "发起角色调整",
      hint: "新增或修改角色档案，转到对话区确认。",
      prompt: "我想新增或调整角色档案。请先根据当前作品设定帮我梳理修改方案。",
    },
    foreshadowing: {
      label: "发起伏笔调整",
      hint: "新增或调整伏笔，转到对话区确认。",
      prompt: "我想调整或新增伏笔",
    },
    rule: {
      label: "发起规则修订",
      hint: "新增或修订经验规则，转到对话区确认。",
      prompt: "我想新增或修订一条经验规则。请先根据当前作品风格和设定给出建议。",
    },
  },
  aliasPrefix: "别名：",
} as const;

// ============================================================
// 阅读模式
// ============================================================

export const READING = {
  totalWordsLabel: "全书有效字数",
  chapterWordsLabel: "本章有效字数",
  wordsUnit: "字",
  shortChapterBadge: "短章",
  emptyChapterBadge: "待补足",
  milestoneProgressLabel: "P1 进度",
  milestoneMetLabel: "已达 P1 目标",
  chaptersBelowMinSuffix: "章待补足",
  emptyChapterBody: "本章尚无已采纳正文，待补足。",
  sceneEmptyBody: "（该场景暂无已采纳正文）",
  exportLabel: "导出全书",
  exportInProgress: "导出中…",
  exportSuccessPrefix: "已导出到",
  exportFailurePrefix: "导出失败：",
  exportDialogTitle: "导出全书",
  exportSelectDirectoryLabel: "选择导出目录",
  exportSelectDirectoryPrompt: "请选择保存导出文件的文件夹",
  exportProgressLabel: "导出进度",
  exportSuccessTitle: "导出完成",
  exportErrorTitle: "导出失败",
  exportCloseLabel: "关闭",
  exportConfirmLabel: "确定",
} as const;

// ============================================================
// Memo 系统
// ============================================================

export const MEMORY = {
  pageTitle: "记忆管理",
  createButton: "+ 新建记忆",
  backToWorkbench: "返回工作台",
  workbenchEntry: "记忆",
  createTitle: "新建记忆",
  editTitle: "编辑记忆",
  detailTitle: "记忆详情",
  noContent: "暂无记忆",
  searchPlaceholder: "搜索记忆...",
  typeLabel: "类型",
  scopeLabel: "作用域",
  statusLabel: "状态",
  confirmAction: "确认",
  lockAction: "锁定",
  unlockAction: "解锁",
  deprecateAction: "标记过期",
  archiveAction: "归档",
  weightLabel: "权重",
  validityLabel: "有效范围",
  traceTitle: "引用与治理追溯",
  traceLoading: "追溯加载中...",
  traceEmpty: "暂无引用或治理记录",
  traceNoReason: "未记录说明",
  traceSceneLabels: {
    memory_lifecycle: "治理动作",
    memory_lifecycle_blocked: "治理阻止",
    dialogue_context: "对话引用",
    recall: "召回引用",
  },
  // 记忆列表视觉与扫描语义（AU-09 记忆列表 UX 重构）
  list: {
    keywordPlaceholder: "搜索记忆…",
    allTypes: "全部类型",
    allScopes: "全部范围",
    allStatuses: "全部状态",
    lockedAll: "锁定（全部）",
    lockedYes: "已锁定",
    lockedNo: "未锁定",
    empty: "暂无记忆，点击「新建记忆」开始。",
    loading: "加载中…",
    columns: {
      content: "内容",
      type: "类型",
      scope: "范围",
      status: "状态",
      recall: "召回",
      locked: "锁定",
    },
    recallable: "可召回",
    notRecallable: "不召回",
    lockedIcon: "已锁定",
    unlockedMark: "—",
  },
  typeLabels: {
    WORLD_RULE: "世界观规则",
    CHARACTER_PROFILE: "人物设定",
    CURRENT_STATE: "当前状态",
    RELATIONSHIP: "人物关系",
    PLOT_FACT: "剧情事实",
    FORESHADOWING: "伏笔",
    STYLE_RULE: "写作风格",
    CONSTRAINT: "创作约束",
    AUTHOR_PREFERENCE: "作者偏好",
    IDEA: "灵感",
    DRAFT_CONTEXT: "草稿上下文",
  } as Record<string, string>,
  statusLabels: {
    DRAFT: "草稿",
    CONFIRMED: "已确认",
    STABILIZED: "已稳定",
    CONFLICTED: "有冲突",
    DEPRECATED: "已弃用",
    ARCHIVED: "已归档",
  } as Record<string, string>,
  scopeLabels: {
    GLOBAL: "全局",
    WORK: "整部作品",
    VOLUME: "当前卷",
    ARC: "故事线",
    CHAPTER: "当前章",
    SESSION: "当前会话",
  } as Record<string, string>,
} as const;

// ============================================================
// Workbench
// ============================================================

export const WORKBENCH_COPY = {
  welcomeMessage:
    "欢迎使用 AI Novel Studio！\n\n" +
    "这是一款对话式小说创作工具。你可以：\n" +
    "• 聊聊创作方向，我会帮你探索\n" +
    "• 让我帮你生成角色设定、剧情草案\n" +
    "• 需要确认的重要操作我会明确提示\n\n" +
    "输入你的想法，开始创作吧！",
  inputPlaceholder: "输入你的想法...（例如：我想写一部赛博修仙小说）",
  sendButton: "发送",
  thinking: "AI 思考中...",
  connectionOffline: "服务离线",
  connectionOnline: "已连接",
  llmChecking: "检测中…",
  llmConnected: "LLM 已连接",
  llmDisconnected: "LLM 未连接",
  llmProviderUnknown: "未配置模型",
  phaseCompleted: "已完成",
  phaseAwaiting: "等待你的操作",
  statusConversational: "对话中",
  statusNeedsClarification: "需要补充信息",
  statusNeedsConfirmation: "需要确认",
  actionConfirm: "确认",
  actionReject: "拒绝",
  actionCancel: "取消",
  actionContinue: "继续对话",
  candidateTitle: "候选方向",
  errorSendFailed: "发送失败，请重试。",
  errorActionFailed: "操作失败，请重试。",
} as const;
